// Crest Range Properties — content translations (listings/hoods/articles/testimonials)
export const CONTENT = {
ar: {
listings: {
'saadiyat-villa': { addr:"فيلا 22، حِد السعديات، جزيرة السعديات", title:'فيلا الشاطئ المميزة', desc:'فيلا خاصة على الشاطئ في أكثر مناطق السعديات خصوصية: صالة بارتفاع مضاعف، مسبح إنفينيتي غربي، أجنحة للخدم ووصول مباشر إلى الرمال.', highlight:'شاطئ خاص | شاغرة عند النقل | بائع جاد', prime:'حِد السعديات تضم أكثر شواطئ الجزيرة خصوصية — اللوفر أبوظبي على بُعد 8 دقائق، ووسط المدينة على بُعد 20 دقيقة، والشاطئ عند نهاية الحديقة.', feats:['وصول خاص للشاطئ','مسبح إنفينيتي','منزل ذكي','غرفة خادمة','مرآب لثلاث سيارات','عضوية نادي الشاطئ'], amen:['نادي شاطئ السعديات','صالة رياضية وسبا','أمن على مدار الساعة','حدائق منسّقة','مواقف مغطاة'] },
'corniche-ph': { addr:"بنتهاوس 4101، باي ريزيدنسز، شارع الكورنيش الغربي", title:'بنتهاوس سماء الكورنيش', desc:'بنتهاوس بطابق كامل يطل على الكورنيش بإطلالة 270° على الخليج، وتراس بمساحة 1,400 قدم مربعة وردهة مصعد خاصة.', highlight:'طابق كامل | إطلالة بحرية 270° | واحد من أربعة فقط', prime:'الكورنيش هو عنوان أبوظبي الكلاسيكي — ثمانية كيلومترات على الواجهة البحرية، ودقائق من الأعمال المركزية وقصر الحصن.', feats:['مصعد خاص','إطلالة بحرية 270°','تراس 1,400 قدم²','برج بخدمة كونسيرج','غرفة نبيذ'], amen:['صف سيارات (فاليه)','صالة للسكان','مسبح إنفينيتي','كونسيرج 24/7','سينما خاصة'] },
'mamsha-apt': { addr:"شقة 312، مبنى 5، ممشى السعديات", title:'شقة ممشى السعديات', desc:'وحدة زاوية على الشاطئ على خطوات من اللوفر أبوظبي، بواجهات زجاجية كاملة وسجل إيجاري يتفوق على متوسط المنطقة بنسبة 12%.', highlight:'واجهة شاطئية | وحدة زاوية | سجل إيجاري قوي', prime:'ممشى السعديات هو الواجهة الثقافية البحرية للحي — اللوفر ونوادي الشاطئ ومطاعم الممشى تحت شرفتك.', feats:['واجهة شاطئية','وحدة زاوية','حي اللوفر','شرفة 320 قدم²','طلب إيجاري مرتفع'], amen:['وصول مباشر للشاطئ','متاجر الممشى','صالة ومسابح','مواقف قبو'] },
'yas-townhouse': { addr:"تاون هاوس 27، الداليا، ياس أيكرز، جزيرة ياس", title:'تاون هاوس ياس أيكرز', desc:'تاون هاوس مطل على ملعب الغولف بحديقة منسّقة وخصوصية صف واحد — تسليم 2024 وما زال ضمن ضمان المطوّر.', highlight:'إطلالة غولف | صف واحد | ضمان المطوّر', prime:'ياس أيكرز على الشاطئ الشمالي الهادئ لجزيرة ياس — الغولف عند الباب، والمدارس داخل المجتمع، والترفيه على بُعد خمس دقائق.', feats:['إطلالة على الغولف','صف واحد','حديقة منسّقة','ضمان المطوّر','مسابح المجتمع'], amen:['نادي الغولف','مسابح المجتمع','مدارس قريبة','مسارات دراجات','ساحة متاجر'] },
'waters-edge': { addr:"شقة 908، مبنى 4، ووترز إيدج، خليج ياس", title:'جناح ووترز إيدج المطل على الماء', desc:'تذكرة الدخول إلى واجهة ياس المائية — مؤجَّرة بـ 68 ألف درهم سنوياً بعائد إجمالي 6.9% من اليوم الأول.', highlight:'مؤجَّرة بعائد 6.9% | ممشى الواجهة المائية', prime:'ووترز إيدج يطل على ممشى خليج ياس — اتحاد أرينا والمطاعم والشاطئ على بُعد خطوات.', feats:['ممشى الواجهة المائية','مؤجَّرة بعائد 6.9%','منطقة خليج ياس','صالة ومسابح'], amen:['متاجر الممشى','صالة ومسابح','مناطق شواء','مواقف مغطاة'] },
'reem-2br': { addr:"شقة 3304، سكاي تاور، شمس أبوظبي، جزيرة الريم", title:'شقة بغرفتين في سكاي تاور', desc:'طابق مرتفع في برج ريم المعروف: إطلالات على البحر والأفق، تكييف مركزي مشمول، وبوتيك مول في البوديوم. حتى 4 شيكات.', highlight:'تكييف مشمول | طابق مرتفع | 4 شيكات', prime:'جزيرة الريم سكنٌ بين ناطحات السحاب على دقائق من الأعمال المركزية — جسور مباشرة إلى المريّة المالية.', feats:['التكييف مشمول','طابق مرتفع','4 شيكات','مول في البوديوم','إطلالة بحرية'], amen:['بوتيك مول','مسبح إنفينيتي','صالة رياضية','أمن 24/7'] },
'raha-1br': { addr:"شقة 214، النسيم ب، البندر، شاطئ الراحة", title:'شقة مارينا البندر', desc:'شقة بغرفة نوم على واجهة المارينا بشرفة ملتفة تطل على اليخوت — سيراً إلى الشاطئ و15 دقيقة إلى المطار.', highlight:'إطلالة مارينا | شرفة ملتفة | متاحة الآن', prime:'شاطئ الراحة يمتد على محور E10 — شاطئ ومارينا ومتاجر في مخطط واحد، على 15 دقيقة من المطار.', feats:['إطلالة على المارينا','شرفة ملتفة','وصول للشاطئ','مواقف مغطاة'], amen:['مراسي يخوت','وصول للشاطئ','صالة ومسابح','مقاهٍ ومتاجر'] },
'maryah-office': { addr:"الطابق 9، مبنى جيت بريسينكت 4، ساحة ADGM، جزيرة المريّة", title:'مكتب فئة A بطابق كامل', desc:'طابق كامل مجهّز في منطقة سوق أبوظبي العالمي المالية — أرضيات مرفوعة و40 موقفاً وإطلالات مائية من ثلاث جهات.', highlight:'عنوان ADGM | مجهّز | 40 موقفاً', prime:'جزيرة المريّة هي المنطقة المالية الحرة في أبوظبي — محاكم ADGM والغاليريا وفنادق الخمس نجوم عند العتبة.', feats:['عنوان ADGM','مجهّز ومفروش','40 موقفاً','أرضيات مرفوعة','إطلالات من ثلاث جهات'], amen:['اتصال بالغاليريا','قاعات اجتماعات','صف سيارات (فاليه)','خدمات مبنى 24/7'] }
},
hoods: { saadiyat:'متاحف ونوادي شاطئية — جزيرة الأسعار القياسية.', yas:'عاصمة الترفيه مع فرص قيمة على الواجهة المائية.', reem:'سكن بين ناطحات السحاب، دقائق من الأعمال المركزية.', corniche:'العنوان الكلاسيكي على الماء.' },
articles: { q2:{tag:'تقرير السوق', title:'أبوظبي الربع الثاني 2026: أسعار الفلل ترتفع 9.4% — وما زالت مقوَّمة بأقل من قيمتها'}, 'saadiyat-yas':{tag:'دليل المستثمر', title:'السعديات أم ياس: أين تتجه الأموال الذكية هذا العام'}, offplan:{tag:'إطلاقات جديدة', title:'خمسة مشاريع على الخريطة تستحق دفعتك هذا الصيف'}, golden:{tag:'أدلة', title:'الإقامة الذهبية عبر العقار: قواعد 2026 ببساطة'}, cheques:{tag:'الإيجار', title:'شيك واحد أم أربعة؟ كيف تحرّك شروط الدفع إيجارات أبوظبي'} },
testi: [
 {q:'أدرجنا العقار يوم الثلاثاء، وثلاثة عروض بحلول الجمعة، وأغلقنا فوق السعر المطلوب. بعت واشتريت في ثلاث دول — لم أرَ هذه السرعة قط.', role:'بيع، فلل شاطئ السعديات'},
 {q:'عاينت عن بُعد من لندن بجولة فيديو، وتفاوضت عبر واتساب ووقّعت خلال أسبوع. عائد صافٍ 7.1% كما هو متوقع تماماً.', role:'مستثمر، جزيرة الريم'},
 {q:'ردّ الكونسيرج في الحادية عشرة ليلاً، وحجز معاينتي للتاسعة صباحاً، والوكيل كان يعرف ميزانيتي وقائمتي مسبقاً. سلاسة تامة.', role:'استئجار، شاطئ الراحة'}
]
},
hi: {
listings: {
'saadiyat-villa': { addr:"विला 22, हिद अल सादियात, सादियात द्वीप", title:'सिग्नेचर बीच विला', desc:'सादियात के सबसे निजी एन्क्लेव में समुद्र-तट विला: डबल-हाइट लिविंग, पश्चिममुखी इनफिनिटी पूल, स्टाफ क्वार्टर और सीधे रेत तक पहुँच।', highlight:'निजी समुद्र-तट | ट्रांसफर पर खाली | इच्छुक विक्रेता', prime:'हिद अल सादियात में द्वीप का सबसे संरक्षित तट है — लूव्र अबू धाबी 8 मिनट, डाउनटाउन 20 मिनट, और बगीचे के छोर पर समुद्र।', feats:['निजी बीच एक्सेस','इनफिनिटी पूल','स्मार्ट होम','मेड रूम','3-कार गैराज','बीच क्लब सदस्यता'], amen:['सादियात बीच क्लब','जिम व स्पा','24/7 सुरक्षा','लैंडस्केप गार्डन','कवर्ड पार्किंग'] },
'corniche-ph': { addr:"पेंटहाउस 4101, बे रेज़िडेंसेज़, कॉर्निश रोड वेस्ट", title:'कॉर्निश स्काई पेंटहाउस', desc:'कॉर्निश के ऊपर पूरा फ्लोर: 270° खाड़ी दृश्य, 1,400 वर्ग फुट की छत और निजी लिफ्ट लॉबी।', highlight:'पूरा फ्लोर | 270° समुद्री दृश्य | केवल चार में से एक', prime:'कॉर्निश अबू धाबी का क्लासिक पता है — आठ किलोमीटर वॉटरफ्रंट, सीबीडी और क़स्र अल होस्न से मिनटों की दूरी।', feats:['निजी लिफ्ट','270° समुद्री दृश्य','1,400 वर्गफुट टेरेस','कंसीयज टावर','वाइन रूम'], amen:['वैले पार्किंग','रेज़िडेंट लाउंज','इनफिनिटी पूल','24/7 कंसीयज','निजी सिनेमा'] },
'mamsha-apt': { addr:"अपार्टमेंट 312, बिल्डिंग 5, ममशा अल सादियात", title:'ममशा अल सादियात रेज़िडेंस', desc:'लूव्र अबू धाबी से कुछ कदम पर समुद्र-तट कॉर्नर यूनिट — फुल-हाइट ग्लेज़िंग और सामुदायिक औसत से 12% बेहतर किराया इतिहास।', highlight:'बीचफ्रंट | कॉर्नर यूनिट | मज़बूत किराया इतिहास', prime:'ममशा अल सादियात इस ज़िले का सांस्कृतिक समुद्री मोर्चा है — लूव्र, बीच क्लब और बोर्डवॉक डाइनिंग आपकी बालकनी के नीचे।', feats:['बीचफ्रंट','कॉर्नर यूनिट','लूव्र ज़िला','320 वर्गफुट बालकनी','उच्च किराया माँग'], amen:['सीधी बीच पहुँच','बोर्डवॉक रिटेल','जिम व पूल','बेसमेंट पार्किंग'] },
'yas-townhouse': { addr:"TH-27, द डेहलियास, यास एकर्स, यास द्वीप", title:'यास एकर्स गार्डन टाउनहाउस', desc:'गोल्फ-कोर्स की ओर मुख वाला टाउनहाउस, लैंडस्केप गार्डन और सिंगल-रो निजता — 2024 में हैंडओवर, अभी भी डेवलपर वारंटी में।', highlight:'गोल्फ व्यू | सिंगल रो | डेवलपर वारंटी', prime:'यास एकर्स यास द्वीप के शांत उत्तरी तट पर है — दरवाज़े पर गोल्फ, कम्युनिटी में स्कूल, और मनोरंजन पाँच मिनट दूर।', feats:['गोल्फ कोर्स व्यू','सिंगल रो','लैंडस्केप गार्डन','डेवलपर वारंटी','कम्युनिटी पूल'], amen:['गोल्फ क्लब','कम्युनिटी पूल','नज़दीकी स्कूल','साइक्लिंग ट्रैक','रिटेल प्लाज़ा'] },
'waters-edge': { addr:"अपार्टमेंट 908, बिल्डिंग 4, वाटर्स एज, यास बे", title:'वाटर्स एज वॉटरफ्रंट सुइट', desc:'यास द्वीप वॉटरफ्रंट का प्रवेश टिकट — AED 68 हज़ार/वर्ष पर किरायेदार सहित, पहले दिन से 6.9% सकल यील्ड।', highlight:'किरायेदार सहित 6.9% यील्ड | वॉटरफ्रंट प्रोमेनेड', prime:'वाटर्स एज यास बे प्रोमेनेड के सामने है — एतिहाद एरीना, डाइनिंग और बीच पैदल दूरी पर।', feats:['वॉटरफ्रंट प्रोमेनेड','किरायेदार सहित 6.9% यील्ड','यास बे ज़िला','जिम व पूल'], amen:['प्रोमेनेड रिटेल','जिम व पूल','बीबीक्यू डेक','कवर्ड पार्किंग'] },
'reem-2br': { addr:"अपार्टमेंट 3304, स्काई टावर, शम्स अबू धाबी, अल रीम द्वीप", title:'स्काई टावर दो-बेडरूम', desc:'रीम के लैंडमार्क टावर में ऊँची मंज़िल: समुद्र-और-स्काईलाइन दृश्य, चिलर शामिल, पोडियम में बुटीक मॉल। 4 चेक तक।', highlight:'चिलर शामिल | ऊँची मंज़िल | 4 चेक', prime:'अल रीम द्वीप सीबीडी से मिनटों की दूरी पर स्काईलाइन लिविंग है — पुल सीधे अल मरिया के वित्तीय ज़िले तक।', feats:['चिलर शामिल','ऊँची मंज़िल','4 चेक','पोडियम में मॉल','समुद्री दृश्य'], amen:['बुटीक मॉल पोडियम','इनफिनिटी पूल','जिम','24/7 सुरक्षा'] },
'raha-1br': { addr:"अपार्टमेंट 214, अल नसीम B, अल बंदर, अल राहा बीच", title:'अल बंदर मरीना अपार्टमेंट', desc:'यॉट्स के ऊपर रैपअराउंड बालकनी वाला मरीना-फ्रंट वन-बेड — बीच तक पैदल, हवाई अड्डे तक 15 मिनट।', highlight:'मरीना व्यू | रैपअराउंड बालकनी | अभी उपलब्ध', prime:'अल राहा बीच E10 कॉरिडोर के साथ है — एक ही मास्टरप्लान में बीच, मरीना और रिटेल, एयरपोर्ट से 15 मिनट।', feats:['मरीना व्यू','रैपअराउंड बालकनी','बीच एक्सेस','कवर्ड पार्किंग'], amen:['मरीना बर्थ','बीच एक्सेस','जिम व पूल','कैफ़े व रिटेल'] },
'maryah-office': { addr:"लेवल 9, गेट प्रिसिंक्ट बिल्डिंग 4, ADGM स्क्वायर, अल मरिया द्वीप", title:'फुल-फ्लोर ग्रेड A ऑफिस', desc:'ADGM वित्तीय ज़िले में फिटेड पूरा फ्लोर — रेज़्ड फ्लोर, 40 पार्किंग और तीन ओर से पानी के दृश्य।', highlight:'ADGM पता | फिटेड | 40 पार्किंग', prime:'अल मरिया द्वीप अबू धाबी का वित्तीय फ्री ज़ोन है — ADGM कोर्ट, द गैलेरिया और पाँच-सितारा होटल दरवाज़े पर।', feats:['ADGM पता','फिटेड व फर्निश्ड','40 पार्किंग','रेज़्ड फ्लोर','तीन ओर खुला'], amen:['द गैलेरिया से जुड़ाव','कॉन्फ्रेंस सुविधाएँ','वैले पार्किंग','24/7 भवन सेवाएँ'] }
},
hoods: { saadiyat:'संग्रहालय, बीच क्लब — रिकॉर्ड कीमतों का द्वीप।', yas:'मनोरंजन की राजधानी, वॉटरफ्रंट वैल्यू के अवसर।', reem:'स्काईलाइन लिविंग, सीबीडी से मिनटों दूर।', corniche:'पानी के किनारे का क्लासिक पता।' },
articles: { q2:{tag:'मार्केट रिपोर्ट', title:'अबू धाबी Q2 2026: विला कीमतें 9.4% ऊपर — फिर भी कम आँकी गईं'}, 'saadiyat-yas':{tag:'निवेशक गाइड', title:'सादियात बनाम यास: इस साल समझदार पैसा कहाँ जा रहा है'}, offplan:{tag:'नए लॉन्च', title:'इस गर्मी आपकी डिपॉज़िट के लायक पाँच ऑफ-प्लान लॉन्च'}, golden:{tag:'गाइड', title:'प्रॉपर्टी से गोल्डन वीज़ा: 2026 के नियम, आसान भाषा में'}, cheques:{tag:'किराया', title:'एक चेक या चार? भुगतान शर्तें अबू धाबी के किराये कैसे बदलती हैं'} },
testi: [
 {q:'मंगलवार को लिस्ट किया, शुक्रवार तक तीन ऑफ़र, और आस्किंग से ऊपर क्लोज़। मैंने तीन देशों में खरीदा-बेचा है — इतनी तेज़ी कभी नहीं देखी।', role:'बिक्री, सादियात बीच विला'},
 {q:'लंदन से वीडियो वॉकथ्रू पर देखा, व्हाट्सऐप पर मोल-भाव किया और एक हफ्ते में साइन किया। 7.1% नेट यील्ड, बिल्कुल अनुमान के मुताबिक।', role:'निवेशक, अल रीम द्वीप'},
 {q:'उनके कंसीयज ने रात 11 बजे जवाब दिया, सुबह 9 की विज़िट बुक की, और एजेंट को मेरा बजट व शॉर्टलिस्ट पहले से पता था। एकदम सहज।', role:'किराया, अल राहा बीच'}
]
},
zh: {
listings: {
'saadiyat-villa': { addr:"萨迪亚特岛 Hidd Al Saadiyat 22号别墅", title:'尊享海滩别墅', desc:'位于萨迪亚特最私密社区的海滨别墅：挑高客厅、朝西无边泳池、员工房，可直达沙滩。', highlight:'私家海滩 | 过户即空置 | 卖家诚意出售', prime:'Hidd Al Saadiyat 拥有岛上最受保护的海岸线——8分钟到卢浮宫阿布扎比，20分钟到市中心，花园尽头即是沙滩。', feats:['私家海滩','无边泳池','智能家居','佣人房','三车位车库','海滩俱乐部会籍'], amen:['萨迪亚特海滩俱乐部','健身房及水疗','24/7安保','景观花园','有盖停车位'] },
'corniche-ph': { addr:"滨海路西 Bay Residences 4101顶层公寓", title:'滨海路空中顶层公寓', desc:'俯瞰滨海路的整层顶层公寓：270°海湾景观、1,400平方英尺露台及私人电梯厅。', highlight:'整层 | 270°海景 | 全楼仅四套之一', prime:'滨海路是阿布扎比的经典地址——八公里滨水岸线，距CBD和侯森宫仅数分钟。', feats:['私人电梯','270°海景','1,400平方英尺露台','礼宾大厦','藏酒室'], amen:['代客泊车','住户会所','无边泳池','24/7礼宾','私人影院'] },
'mamsha-apt': { addr:"Mamsha Al Saadiyat 5号楼312室", title:'Mamsha Al Saadiyat 公寓', desc:'距卢浮宫阿布扎比几步之遥的海滨转角单元，全高玻璃幕墙，租金表现高出社区均值12%。', highlight:'一线海滨 | 转角单元 | 租赁记录优异', prime:'Mamsha Al Saadiyat 是该区的文化海滨——卢浮宫、海滩俱乐部和木栈道餐饮就在阳台下方。', feats:['一线海滨','转角单元','卢浮宫片区','320平方英尺阳台','租赁需求旺盛'], amen:['直达海滩','木栈道商铺','健身房及泳池','地下停车'] },
'yas-townhouse': { addr:"亚斯岛 Yas Acres The Dahlias TH-27", title:'Yas Acres 花园联排别墅', desc:'面向高尔夫球场的联排别墅，景观花园、单排私密性——2024年交付，仍在开发商保修期内。', highlight:'高尔夫景观 | 单排 | 开发商保修', prime:'Yas Acres 位于亚斯岛安静的北岸——门口即高尔夫，社区内有学校，五分钟到达岛上娱乐区。', feats:['高尔夫球场景观','单排','景观花园','开发商保修','社区泳池'], amen:['高尔夫俱乐部','社区泳池','学校临近','自行车道','零售广场'] },
'waters-edge': { addr:"亚斯湾 Water's Edge 4号楼908室", title:"Water's Edge 滨水套房", desc:'亚斯岛滨水区的入场券——现以每年6.8万迪拉姆出租，首日即获6.9%毛收益。', highlight:'在租 6.9%收益 | 滨水长廊', prime:"Water's Edge 面向亚斯湾长廊——阿提哈德体育馆、餐饮与海滩步行可达。", feats:['滨水长廊','在租 6.9%收益','亚斯湾片区','健身房及泳池'], amen:['长廊商铺','健身房及泳池','烧烤平台','有盖停车位'] },
'reem-2br': { addr:"瑞姆岛 Shams Abu Dhabi Sky Tower 3304室", title:'Sky Tower 两居室', desc:'瑞姆地标塔楼高层：海景与天际线景观，含中央空调费，裙楼即 Boutik 商场。最多4张支票。', highlight:'含空调费 | 高层 | 4张支票', prime:'瑞姆岛是距CBD仅数分钟的天际线生活——大桥直通玛丽亚岛金融区。', feats:['含中央空调费','高层','4张支票','裙楼商场','海景'], amen:['Boutik 商场裙楼','无边泳池','健身房','24/7安保'] },
'raha-1br': { addr:"拉哈海滩 Al Bandar Al Naseem B座214室", title:'Al Bandar 码头公寓', desc:'码头一线一居室，环绕式阳台俯瞰游艇——步行到海滩，15分钟到机场。', highlight:'码头景观 | 环绕阳台 | 即刻入住', prime:'Al Raha Beach 沿E10走廊延展——海滩、码头与零售同在一个总体规划内，距机场15分钟。', feats:['码头景观','环绕式阳台','海滩通道','有盖停车位'], amen:['游艇泊位','海滩通道','健身房及泳池','咖啡馆与商铺'] },
'maryah-office': { addr:"玛丽亚岛 ADGM广场 Gate Precinct 4号楼9层", title:'整层甲级写字楼', desc:'ADGM金融区精装整层——架空地板、40个车位、三面环水景观。', highlight:'ADGM地址 | 精装 | 40个车位', prime:'玛丽亚岛是阿布扎比的金融自由区——ADGM法院、The Galleria 和五星级酒店近在咫尺。', feats:['ADGM地址','精装带家具','40个车位','架空地板','三面采光'], amen:['直通 The Galleria','会议设施','代客泊车','24/7楼宇服务'] }
},
hoods: { saadiyat:'博物馆与海滩俱乐部——创纪录房价之岛。', yas:'娱乐之都，滨水价值洼地。', reem:'天际线生活，数分钟到CBD。', corniche:'水岸经典地址。' },
articles: { q2:{tag:'市场报告', title:'阿布扎比2026年第二季度：别墅价格上涨9.4%——仍被低估'}, 'saadiyat-yas':{tag:'投资指南', title:'萨迪亚特还是亚斯：今年聪明的钱往哪里去'}, offplan:{tag:'新盘发布', title:'今夏值得下订的五个期房项目'}, golden:{tag:'指南', title:'购房获取黄金签证：2026年新规解读'}, cheques:{tag:'租房', title:'一张支票还是四张？付款方式如何影响阿布扎比租金'} },
testi: [
 {q:'周二挂牌，周五收到三个报价，最终高于要价成交。我在三个国家买卖过房产——从没这么快过。', role:'出售，萨迪亚特海滩别墅'},
 {q:'我在伦敦通过视频远程看房，在WhatsApp上谈判，一周内签约。7.1%净收益，与预测完全一致。', role:'投资者，瑞姆岛'},
 {q:'他们的礼宾晚上11点回复，帮我订了早上9点的看房，经纪人早已了解我的预算和清单。无缝衔接。', role:'租房，Al Raha Beach'}
]
},
ru: {
listings: {
'saadiyat-villa': { addr:"Вилла 22, Хидд-аль-Саадият, остров Саадият", title:'Фирменная пляжная вилла', desc:'Частная вилла на первой линии в самом закрытом анклаве Саадията: двусветная гостиная, бассейн-инфинити на запад, комнаты для персонала и прямой выход к песку.', highlight:'Свой пляж | Свободна при передаче | Мотивированный продавец', prime:'Хидд-аль-Саадият — самый охраняемый берег острова: Лувр Абу-Даби в 8 минутах, центр в 20, пляж — в конце сада.', feats:['Свой выход к пляжу','Бассейн-инфинити','Умный дом','Комната для прислуги','Гараж на 3 авто','Членство в пляжном клубе'], amen:['Пляжный клуб Саадията','Спортзал и спа','Охрана 24/7','Ландшафтные сады','Крытый паркинг'] },
'corniche-ph': { addr:"Пентхаус 4101, Bay Residences, Корниш-Роуд Вест", title:'Пентхаус Corniche Sky', desc:'Пентхаус на весь этаж над Корнишем: вид на залив 270°, терраса 1 400 кв. футов и собственный лифтовой холл.', highlight:'Весь этаж | Вид на море 270° | Один из четырёх', prime:'Корниш — классический адрес Абу-Даби: восемь километров набережной, минуты до делового центра и Каср-аль-Хосн.', feats:['Собственный лифт','Вид на море 270°','Терраса 1 400 кв. футов','Башня с консьержем','Винная комната'], amen:['Валет-паркинг','Лаундж для жителей','Бассейн-инфинити','Консьерж 24/7','Частный кинозал'] },
'mamsha-apt': { addr:"Квартира 312, корпус 5, Mamsha Al Saadiyat", title:'Резиденция Mamsha Al Saadiyat', desc:'Угловая квартира на первой линии в шаге от Лувра Абу-Даби: панорамное остекление и арендная история на 12% выше среднего по району.', highlight:'Первая линия | Угловая | Сильная арендная история', prime:'Mamsha Al Saadiyat — культурная набережная района: Лувр, пляжные клубы и рестораны променада под вашим балконом.', feats:['Первая линия','Угловая квартира','Район Лувра','Балкон 320 кв. футов','Высокий арендный спрос'], amen:['Прямой выход к пляжу','Магазины променада','Спортзал и бассейны','Подземный паркинг'] },
'yas-townhouse': { addr:"TH-27, The Dahlias, Yas Acres, остров Яс", title:'Таунхаус Yas Acres Garden', desc:'Таунхаус с видом на гольф-поле, ландшафтным садом и приватностью одного ряда — сдан в 2024-м, ещё на гарантии застройщика.', highlight:'Вид на гольф | Один ряд | Гарантия застройщика', prime:'Yas Acres — тихий северный берег острова Яс: гольф у порога, школы в комьюнити, развлечения острова в пяти минутах.', feats:['Вид на гольф-поле','Один ряд','Ландшафтный сад','Гарантия застройщика','Бассейны комьюнити'], amen:['Гольф-клуб','Бассейны комьюнити','Школы рядом','Велодорожки','Торговая площадь'] },
'waters-edge': { addr:"Квартира 908, корпус 4, Water's Edge, Яс-Бэй", title:"Апартаменты Water's Edge", desc:'Входной билет на набережную острова Яс: сдана за 68 тыс. AED/год — валовая доходность 6,9% с первого дня.', highlight:'Сдана, доходность 6,9% | Набережная', prime:"Water's Edge выходит на променад Яс-Бэй: Etihad Arena, рестораны и пляж в нескольких минутах пешком.", feats:['Набережная-променад','Сдана, доходность 6,9%','Район Яс-Бэй','Спортзал и бассейны'], amen:['Магазины променада','Спортзал и бассейны','Зоны барбекю','Крытый паркинг'] },
'reem-2br': { addr:"Квартира 3304, Sky Tower, Шамс Абу-Даби, остров Аль-Рим", title:'Двухспальная в Sky Tower', desc:'Высокий этаж в знаковой башне Рима: море и панорама города, чиллер включён, Boutik Mall в подиуме. До 4 чеков.', highlight:'Чиллер включён | Высокий этаж | 4 чека', prime:'Аль-Рим — жизнь среди небоскрёбов в минутах от делового центра: мосты ведут прямо в финансовый район Аль-Марии.', feats:['Чиллер включён','Высокий этаж','4 чека','Молл в подиуме','Вид на море'], amen:['Boutik Mall в подиуме','Бассейн-инфинити','Спортзал','Охрана 24/7'] },
'raha-1br': { addr:"Квартира 214, Al Naseem B, Al Bandar, Аль-Раха-Бич", title:'Апартаменты Al Bandar Marina', desc:'Однушка на первой линии марины с круговым балконом над яхтами: пешком до пляжа, 15 минут до аэропорта.', highlight:'Вид на марину | Круговой балкон | Свободна', prime:'Аль-Раха-Бич тянется вдоль коридора E10: пляж, марина и магазины в одном мастер-плане, 15 минут от аэропорта.', feats:['Вид на марину','Круговой балкон','Выход к пляжу','Крытый паркинг'], amen:['Причалы марины','Выход к пляжу','Спортзал и бассейны','Кафе и магазины'] },
'maryah-office': { addr:"Этаж 9, Gate Precinct 4, ADGM Square, остров Аль-Мария", title:'Офис класса А на весь этаж', desc:'Готовый этаж в финансовом районе ADGM: фальшполы, 40 парковочных мест и вода с трёх сторон.', highlight:'Адрес ADGM | С отделкой | 40 паркомест', prime:'Аль-Мария — финансовая свободная зона Абу-Даби: суды ADGM, The Galleria и пятизвёздочные отели у порога.', feats:['Адрес ADGM','С отделкой и мебелью','40 паркомест','Фальшполы','Свет с трёх сторон'], amen:['Переход в The Galleria','Конференц-залы','Валет-паркинг','Сервис здания 24/7'] }
},
hoods: { saadiyat:'Музеи, пляжные клубы — остров рекордных цен.', yas:'Столица развлечений и недооценённая набережная.', reem:'Жизнь среди небоскрёбов, минуты от центра.', corniche:'Классический адрес у воды.' },
articles: { q2:{tag:'Отчёт о рынке', title:'Абу-Даби, II кв. 2026: виллы +9,4% — и всё ещё недооценены'}, 'saadiyat-yas':{tag:'Гид инвестора', title:'Саадият или Яс: куда в этом году идут умные деньги'}, offplan:{tag:'Новые проекты', title:'Пять офф-план проектов, достойных вашего депозита этим летом'}, golden:{tag:'Гиды', title:'«Золотая виза» через недвижимость: правила 2026 года'}, cheques:{tag:'Аренда', title:'Один чек или четыре? Как условия оплаты двигают аренду в Абу-Даби'} },
testi: [
 {q:'Выставили во вторник, три предложения к пятнице, закрыли выше запрашиваемой цены. Я покупал и продавал в трёх странах — так быстро не было никогда.', role:'Продажа, Saadiyat Beach Villas'},
 {q:'Смотрел удалённо из Лондона по видео, торговался в WhatsApp и подписал за неделю. Чистая доходность 7,1% — ровно как обещали.', role:'Инвестор, остров Аль-Рим'},
 {q:'Их консьерж ответил в 23:00, записал меня на показ к 9 утра, а агент уже знал мой бюджет и шорт-лист. Безупречно.', role:'Аренда, Аль-Раха-Бич'}
]
},
fr: {
listings: {
'saadiyat-villa': { addr:"Villa 22, Hidd Al Saadiyat, île de Saadiyat", title:'Villa signature sur la plage', desc:'Villa privée en front de mer dans l\u2019enclave la plus protégée de Saadiyat : séjour double hauteur, piscine à débordement plein ouest, quartiers du personnel et accès direct au sable.', highlight:'Plage privée | Libre au transfert | Vendeur motivé', prime:'Hidd Al Saadiyat détient la plage la plus préservée de l\u2019île — le Louvre Abu Dhabi à 8 minutes, le centre à 20, et le sable au bout du jardin.', feats:['Accès plage privé','Piscine à débordement','Maison connectée','Chambre de service','Garage 3 voitures','Adhésion beach club'], amen:['Saadiyat Beach Club','Salle de sport et spa','Sécurité 24/7','Jardins paysagers','Parking couvert'] },
'corniche-ph': { addr:"Penthouse 4101, Bay Residences, Corniche Road Ouest", title:'Penthouse Corniche Sky', desc:'Penthouse sur un étage entier au-dessus de la Corniche : vue à 270° sur le Golfe, terrasse de 1 400 pieds carrés et hall d\u2019ascenseur privé.', highlight:'Étage entier | Vue mer 270° | L\u2019un des quatre seulement', prime:'La Corniche est l\u2019adresse classique d\u2019Abu Dhabi — huit kilomètres de front de mer, à quelques minutes du CBD et de Qasr Al Hosn.', feats:['Ascenseur privé','Vue mer 270°','Terrasse 1 400 pi²','Tour avec conciergerie','Cave à vin'], amen:['Voiturier','Salon des résidents','Piscine à débordement','Conciergerie 24/7','Cinéma privé'] },
'mamsha-apt': { addr:"Appartement 312, bâtiment 5, Mamsha Al Saadiyat", title:'Résidence Mamsha Al Saadiyat', desc:'Unité d\u2019angle en front de mer à deux pas du Louvre Abu Dhabi : vitrages toute hauteur et historique locatif supérieur de 12 % à la moyenne du quartier.', highlight:'Front de mer | Unité d\u2019angle | Solide historique locatif', prime:'Mamsha Al Saadiyat est le front de mer culturel du quartier — le Louvre, les beach clubs et les restaurants de la promenade sous votre balcon.', feats:['Front de mer','Unité d\u2019angle','Quartier du Louvre','Balcon 320 pi²','Forte demande locative'], amen:['Accès direct plage','Commerces de la promenade','Salle de sport et piscines','Parking en sous-sol'] },
'yas-townhouse': { addr:"TH-27, The Dahlias, Yas Acres, île de Yas", title:'Maison de ville Yas Acres', desc:'Maison de ville face au golf avec jardin paysager et intimité d\u2019une rangée unique — livrée en 2024, encore sous garantie promoteur.', highlight:'Vue golf | Rangée unique | Garantie promoteur', prime:'Yas Acres occupe la rive nord paisible de Yas Island — golf à la porte, écoles dans la communauté, divertissements à cinq minutes.', feats:['Vue sur le golf','Rangée unique','Jardin paysager','Garantie promoteur','Piscines communes'], amen:['Golf club','Piscines communes','Écoles à proximité','Pistes cyclables','Place commerçante'] },
'waters-edge': { addr:"Appartement 908, bâtiment 4, Water's Edge, Yas Bay", title:'Suite Water\u2019s Edge front d\u2019eau', desc:'Le ticket d\u2019entrée du front de mer de Yas Island — louée 68 k AED/an, soit 6,9 % de rendement brut dès le premier jour.', highlight:'Louée, rendement 6,9 % | Promenade front d\u2019eau', prime:'Water\u2019s Edge donne sur la promenade de Yas Bay — Etihad Arena, restaurants et plage à quelques minutes à pied.', feats:['Promenade front d\u2019eau','Louée, rendement 6,9 %','Quartier Yas Bay','Salle de sport et piscines'], amen:['Commerces de la promenade','Salle de sport et piscines','Espaces barbecue','Parking couvert'] },
'reem-2br': { addr:"Appartement 3304, Sky Tower, Shams Abu Dhabi, île d'Al Reem", title:'Deux-pièces Sky Tower', desc:'Étage élevé dans la tour emblématique de Reem : vues mer et skyline, climatisation incluse, Boutik Mall au podium. Jusqu\u2019à 4 chèques.', highlight:'Clim incluse | Étage élevé | 4 chèques', prime:'Al Reem Island, c\u2019est la vie dans la skyline à quelques minutes du CBD — des ponts mènent droit au quartier financier d\u2019Al Maryah.', feats:['Climatisation incluse','Étage élevé','4 chèques','Centre commercial au podium','Vue mer'], amen:['Podium Boutik Mall','Piscine à débordement','Salle de sport','Sécurité 24/7'] },
'raha-1br': { addr:"Appartement 214, Al Naseem B, Al Bandar, Al Raha Beach", title:'Appartement Al Bandar Marina', desc:'Une chambre face à la marina avec balcon panoramique sur les yachts — plage à pied, aéroport à 15 minutes.', highlight:'Vue marina | Balcon panoramique | Disponible', prime:'Al Raha Beach longe le corridor E10 — plage, marina et commerces dans un même plan directeur, à 15 minutes de l\u2019aéroport.', feats:['Vue marina','Balcon panoramique','Accès plage','Parking couvert'], amen:['Postes d\u2019amarrage','Accès plage','Salle de sport et piscines','Cafés et commerces'] },
'maryah-office': { addr:"Niveau 9, Gate Precinct 4, ADGM Square, île d'Al Maryah", title:'Bureau Grade A, étage entier', desc:'Étage entier aménagé dans le district financier ADGM — planchers techniques, 40 places de parking et vues sur l\u2019eau sur trois côtés.', highlight:'Adresse ADGM | Aménagé | 40 places', prime:'Al Maryah Island est la zone franche financière d\u2019Abu Dhabi — tribunaux ADGM, The Galleria et hôtels cinq étoiles au pied de l\u2019immeuble.', feats:['Adresse ADGM','Aménagé et meublé','40 places de parking','Planchers techniques','Triple exposition'], amen:['Accès The Galleria','Salles de conférence','Voiturier','Services 24/7'] }
},
hoods: { saadiyat:'Musées, beach clubs — l\u2019île des prix records.', yas:'Capitale du divertissement, valeur sûre en front d\u2019eau.', reem:'Vivre dans la skyline, à minutes du CBD.', corniche:'L\u2019adresse classique au bord de l\u2019eau.' },
articles: { q2:{tag:'Rapport de marché', title:'Abu Dhabi T2 2026 : villas à +9,4 % — et toujours sous-évaluées'}, 'saadiyat-yas':{tag:'Guide investisseur', title:'Saadiyat ou Yas : où va l\u2019argent avisé cette année'}, offplan:{tag:'Nouveaux lancements', title:'Cinq lancements sur plan qui méritent votre dépôt cet été'}, golden:{tag:'Guides', title:'Golden Visa par l\u2019immobilier : les règles 2026, expliquées'}, cheques:{tag:'Location', title:'Un chèque ou quatre ? Comment les modalités de paiement font bouger les loyers'} },
testi: [
 {q:'Mis en vente un mardi, trois offres le vendredi, conclu au-dessus du prix demandé. J\u2019ai acheté et vendu dans trois pays — jamais aussi vite.', role:'Vente, Saadiyat Beach Villas'},
 {q:'J\u2019ai visité à distance depuis Londres en vidéo, négocié sur WhatsApp et signé en une semaine. 7,1 % de rendement net, exactement comme projeté.', role:'Investisseur, Al Reem Island'},
 {q:'Leur concierge a répondu à 23 h, réservé ma visite pour 9 h, et l\u2019agent connaissait déjà mon budget et ma shortlist. Sans couture.', role:'Location, Al Raha Beach'}
]
},
es: {
listings: {
'saadiyat-villa': { addr:"Villa 22, Hidd Al Saadiyat, isla Saadiyat", title:'Villa insignia en la playa', desc:'Villa privada frente al mar en el enclave más resguardado de Saadiyat: salón a doble altura, piscina infinita al oeste, cuartos de servicio y acceso directo a la arena.', highlight:'Playa privada | Libre al transferir | Vendedor motivado', prime:'Hidd Al Saadiyat guarda la playa más protegida de la isla: el Louvre Abu Dhabi a 8 minutos, el centro a 20 y la arena al final del jardín.', feats:['Acceso privado a la playa','Piscina infinita','Casa inteligente','Cuarto de servicio','Garaje para 3 autos','Membresía de beach club'], amen:['Saadiyat Beach Club','Gimnasio y spa','Seguridad 24/7','Jardines paisajísticos','Estacionamiento cubierto'] },
'corniche-ph': { addr:"Ático 4101, Bay Residences, Corniche Road Oeste", title:'Ático Corniche Sky', desc:'Ático de planta completa sobre la Corniche: vistas de 270° al Golfo, terraza de 1.400 pies² y vestíbulo de ascensor privado.', highlight:'Planta completa | Vista al mar 270° | Uno de solo cuatro', prime:'La Corniche es la dirección clásica de Abu Dabi: ocho kilómetros de paseo marítimo, a minutos del CBD y de Qasr Al Hosn.', feats:['Ascensor privado','Vista al mar 270°','Terraza 1.400 pies²','Torre con conserjería','Cava de vinos'], amen:['Valet parking','Salón de residentes','Piscina infinita','Conserjería 24/7','Cine privado'] },
'mamsha-apt': { addr:"Apartamento 312, edificio 5, Mamsha Al Saadiyat", title:'Residencia Mamsha Al Saadiyat', desc:'Unidad de esquina frente al mar a pasos del Louvre Abu Dhabi: cristaleras de suelo a techo e historial de alquiler un 12 % sobre la media.', highlight:'Frente al mar | Esquina | Sólido historial de alquiler', prime:'Mamsha Al Saadiyat es el frente marítimo cultural del distrito: el Louvre, los beach clubs y los restaurantes del paseo bajo su balcón.', feats:['Frente al mar','Unidad de esquina','Distrito del Louvre','Balcón 320 pies²','Alta demanda de alquiler'], amen:['Acceso directo a la playa','Comercios del paseo','Gimnasio y piscinas','Estacionamiento subterráneo'] },
'yas-townhouse': { addr:"TH-27, The Dahlias, Yas Acres, isla Yas", title:'Adosado Yas Acres Garden', desc:'Adosado frente al campo de golf con jardín paisajístico y privacidad de fila única: entregado en 2024, aún con garantía del promotor.', highlight:'Vista al golf | Fila única | Garantía del promotor', prime:'Yas Acres ocupa la tranquila costa norte de Yas Island: golf en la puerta, colegios en la comunidad y el ocio de la isla a cinco minutos.', feats:['Vista al campo de golf','Fila única','Jardín paisajístico','Garantía del promotor','Piscinas comunitarias'], amen:['Club de golf','Piscinas comunitarias','Colegios cercanos','Carriles bici','Plaza comercial'] },
'waters-edge': { addr:"Apartamento 908, edificio 4, Water's Edge, Yas Bay", title:'Suite Water\u2019s Edge frente al agua', desc:'La entrada al waterfront de Yas Island: alquilada en 68 mil AED/año, un 6,9 % de rendimiento bruto desde el primer día.', highlight:'Alquilada, 6,9 % de rendimiento | Paseo marítimo', prime:'Water\u2019s Edge da al paseo de Yas Bay: Etihad Arena, restaurantes y playa a un corto paseo.', feats:['Paseo marítimo','Alquilada, 6,9 % de rendimiento','Distrito Yas Bay','Gimnasio y piscinas'], amen:['Comercios del paseo','Gimnasio y piscinas','Zonas de barbacoa','Estacionamiento cubierto'] },
'reem-2br': { addr:"Apartamento 3304, Sky Tower, Shams Abu Dhabi, isla Al Reem", title:'Dos dormitorios en Sky Tower', desc:'Piso alto en la torre emblemática de Reem: vistas al mar y al skyline, refrigeración incluida y Boutik Mall en el podio. Hasta 4 cheques.', highlight:'Clima incluido | Piso alto | 4 cheques', prime:'Al Reem Island es vida de skyline a minutos del CBD: puentes directos al distrito financiero de Al Maryah.', feats:['Refrigeración incluida','Piso alto','4 cheques','Centro comercial en el podio','Vista al mar'], amen:['Podio Boutik Mall','Piscina infinita','Gimnasio','Seguridad 24/7'] },
'raha-1br': { addr:"Apartamento 214, Al Naseem B, Al Bandar, Al Raha Beach", title:'Apartamento Al Bandar Marina', desc:'Un dormitorio frente a la marina con balcón envolvente sobre los yates: playa a pie y aeropuerto a 15 minutos.', highlight:'Vista a la marina | Balcón envolvente | Disponible', prime:'Al Raha Beach bordea el corredor E10: playa, marina y comercios en un mismo plan maestro, a 15 minutos del aeropuerto.', feats:['Vista a la marina','Balcón envolvente','Acceso a la playa','Estacionamiento cubierto'], amen:['Amarres de marina','Acceso a la playa','Gimnasio y piscinas','Cafés y comercios'] },
'maryah-office': { addr:"Planta 9, Gate Precinct 4, ADGM Square, isla Al Maryah", title:'Oficina Grado A de planta completa', desc:'Planta completa equipada en el distrito financiero ADGM: suelos técnicos, 40 plazas de parking y vistas al agua por tres lados.', highlight:'Dirección ADGM | Equipada | 40 plazas', prime:'Al Maryah Island es la zona franca financiera de Abu Dabi: tribunales ADGM, The Galleria y hoteles cinco estrellas en la puerta.', feats:['Dirección ADGM','Equipada y amueblada','40 plazas de parking','Suelos técnicos','Triple orientación'], amen:['Acceso a The Galleria','Salas de conferencias','Valet parking','Servicios del edificio 24/7'] }
},
hoods: { saadiyat:'Museos y beach clubs: la isla de los precios récord.', yas:'Capital del ocio con oportunidades frente al agua.', reem:'Vida de skyline, a minutos del CBD.', corniche:'La dirección clásica junto al agua.' },
articles: { q2:{tag:'Informe de mercado', title:'Abu Dabi T2 2026: las villas suben un 9,4 % — y siguen infravaloradas'}, 'saadiyat-yas':{tag:'Guía del inversor', title:'Saadiyat o Yas: adónde se mueve el dinero inteligente este año'}, offplan:{tag:'Nuevos lanzamientos', title:'Cinco lanzamientos sobre plano que merecen su depósito este verano'}, golden:{tag:'Guías', title:'Golden Visa a través de la propiedad: las reglas de 2026, explicadas'}, cheques:{tag:'Alquiler', title:'¿Un cheque o cuatro? Cómo mueven los alquileres las condiciones de pago'} },
testi: [
 {q:'Publicado un martes, tres ofertas para el viernes y cierre por encima del precio pedido. He comprado y vendido en tres países: nunca tan rápido.', role:'Venta, Saadiyat Beach Villas'},
 {q:'Lo vi a distancia desde Londres por vídeo, negocié por WhatsApp y firmé en una semana. 7,1 % de rendimiento neto, exactamente lo proyectado.', role:'Inversor, Al Reem Island'},
 {q:'Su conserje respondió a las 23:00, reservó mi visita para las 9:00 y el agente ya conocía mi presupuesto y mi lista. Impecable.', role:'Alquiler, Al Raha Beach'}
]
}
};
